# Installs nomad
# ansible-playbook 20-docker.yml
---
- hosts: master,docker
  gather_facts: no
  remote_user: ubuntu
  become: true
  tasks:
  - name: apt update
    apt:
      update_cache: yes
  - name: apt-transport-https install
    package:
      name: apt-transport-https
      state: present
  - name: ca-certificates install
    package:
      name: ca-certificates
      state: present
  - name: curl install
    package:
      name: curl
      state: present
  - name: gnupg-agent install
    package:
      name: gnupg-agent
      state: present
  - name: apt-key add hashicorp
    shell: "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
    args:
      warn: no
  - name: add-apt-repository hashicorp
    copy:
      content: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
      dest: /etc/apt/sources.list.d/hashicorp.list
  - name: apt update
    apt:
      update_cache: yes
  - name: nomad install
    package:
      name: nomad 
      state: present
